### ISSUE TITLE
Extension Directory Mixed Camel and Lowercase

### ISSUE THREAD

**Issue by British-Systems** [British-Systems/MultiPlug#47]
The folders are both CamelCase and Lowercase within the Extensions directory, this maybe because the differences in the install process.

This is also causing duplicates running under Linux/Mono.

**Comment by Industry4** [comment]
This is likely being caused by the file upload procedure.

**Comment by British-Systems** [comment]
The Extension folder name was the URL name, which works find under Windows where the file system is case insensitive, but under Linux where the file system is case sensitive, would create a new folder.

TODO: Stop using the File System and use the Internal Coms
