### ISSUE TITLE
 Upline/Downline State does not change

### ISSUE THREAD

**Issue by ThoPO** [British-Systems/MultiPlug#60]
We have tried the SMEMA adapter on several machines, e.g. ASYS TRM01, Cencorp 1500,...

But no matter what I do machine start, stop, turn off the status never changes
![image](https://github.com/British-Systems/MultiPlug/assets/16400329/ad210488-bae0-459b-a93a-1eddbc32c453)

**Comment by British-Systems** [comment]
Hello @ThoPO this is the wrong repository for MultiPlug Extensions -> https://github.com/Industry4/MultiPlug.Ext.SMEMA/issues

Please contact hello@4IR.UK
